name: Other issues
description: Use this template for any other issues.
body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: "<!-- A clear and concise description of what the bug is. -->"
    validations:
      required: true
